# Generated by Django 2.0.13 on 2019-05-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20190520_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subjects',
            new_name='subject',
        ),
    ]
