# Generated by Django 2.0.13 on 2019-05-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wordcount',
            field=models.IntegerField(null=True),
        ),
    ]
