# Generated by Django 2.0.13 on 2019-05-27 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0006_post_wordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_check',
            field=models.ManyToManyField(related_name='likes_check', to=settings.AUTH_USER_MODEL),
        ),
    ]
